# Site
repository: helinasangoi/myresume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Helina Sangoi
title: Admin
email: helinasangoi27@gmail.com
# email_title: Email (Email title override)
phone: 7021238887
# phone_title: Phone (Phone title override)
website: https://helinasangoi.github.io/myresume
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  helinasangoi
facebook_username: jekyll
instagram_username: jekyll
linkedin_username: helina-sangoi-a50a6a145

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Areas of strength
    layout: column
    content:
      - layout: center
        border:
        field:
          - name: Teamwork
          - name: Data Management
          - name: Computer Literacy
          - name: Administrative/Office Functions
          - name: Budgeting/Controlling Expenses
          - name: Communication
          - name: Efficient Calendar Management
          - name: Time Management
          - name: Event Planning and Coordination
          - name: Manage Confidential Information
          - name: Client & Employee Relations
          - name: Organizational
          - name: Negotiate Contracts/Procurement
          - name: Problem Analysis/ Resolution
          - name: Meticulous Attention to Detail
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Mash Energy India Pvt Ltd
        sub_title: Admin Incharge & Procurement, Data Analyst
        caption: September 2022  - till Date
        link:
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Managed end-to-end courier shipments, ensuring timely and accurate delivery to specified addresses.
          Handled the packing of samples with meticulous attention to detail.
          Oversaw international shipment documentation, ensuring compliance with global shipping regulations and standards.
      - layout: left
        title: Fortune Tata Motors Pvt. Ltd
        sub_title: Sales Coordinator & Delivery Associate
        caption: March 2021 to September 2022
        link:
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Scheduled appointments for sales and business development discussions.
          Managed automobile sales and utilized company resources to develop a filing system that keeps all active sales files available digitally and in hard copy form.
          Ensured the upkeep of display cars through coordination with various teams.
          Managed the courier register, including incoming and outgoing couriers, and maintained courier slips for bill verification and processing.
          Oversaw the Delivery Department to ensure timely car delivery.
      - layout: left
        title: Euphoria Technologies Pvt Ltd
        sub_title: Admin
        caption: June 2017 to December 2019
        link:
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Managed all aspects of air ticketing, hotel booking, and local logistics for the group.
          Conducted interviews, handled joining formalities, and engaged in employee engagement activities.
          Directed visitors to the appropriate person and office.
          Handled incoming phone calls, including answering, screening, and forwarding calls.
          Provided basic and accurate information in-person and via phone/email.
          Upheld office security by adhering to safety procedures and controlling access via the reception desk, including monitoring the logbook.
          Ordered front office supplies and maintained inventory.
          Updated calendars and scheduled meetings.
          Kept updated records of office expenses and costs.
          Performed other clerical duties such as filing, photocopying, transcribing, and faxing.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Mumbai University
        sub_title: Bachelors of Commerce
        caption: 2001 – 2004
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-left
        title: Maharashtra Board
        sub_title: Higher Secondary Certificate ( HSC )
        caption: 1997 – 2000
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-left
        title: Maharashtra Board
        sub_title: School Cerfificate ( SSC )
        caption: 1987 – 1997
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Achievements**
      *performance* Consistently exceeded sales targets, demonstrating a strong track record in performance.
      *leadership* Promoted to Group Team Leader based on exceptional performance and leadership skills.      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
